# Generated by Django 2.1.4 on 2019-01-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=50)),
                ('sentence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PosRest.Sentence')),
            ],
        ),
    ]
