# Generated by Django 2.1.3 on 2018-12-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='split',
        ),
    ]
