# Generated by Django 2.1.3 on 2018-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(choices=[('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Verb', 'Verb'), ('Others', 'Others')], max_length=100),
        ),
    ]
