# Generated by Django 2.1.3 on 2018-12-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20181227_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Split',
        ),
    ]
