# Generated by Django 2.1.3 on 2018-12-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20181231_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, choices=[('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Verb', 'Verb'), ('Others', 'Others')], max_length=100),
        ),
    ]
